// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7pfeZgBDQYfOZa5ajxR_vk0Wsp-jrL9U',
    appId: '1:960456369743:web:e689258bdb19b9c85bec3a',
    messagingSenderId: '960456369743',
    projectId: 'ta-app-850bd',
    authDomain: 'ta-app-850bd.firebaseapp.com',
    storageBucket: 'ta-app-850bd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiOML88myeJCN7iZpjHC_qWpX3kXWJHFg',
    appId: '1:960456369743:android:894fd78b15e68a9a5bec3a',
    messagingSenderId: '960456369743',
    projectId: 'ta-app-850bd',
    storageBucket: 'ta-app-850bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnvV8iFnpqDWG2-ylmtgj695lWxGhSZd4',
    appId: '1:960456369743:ios:6c33818d89dbaa945bec3a',
    messagingSenderId: '960456369743',
    projectId: 'ta-app-850bd',
    storageBucket: 'ta-app-850bd.firebasestorage.app',
    iosBundleId: 'com.example.spkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnvV8iFnpqDWG2-ylmtgj695lWxGhSZd4',
    appId: '1:960456369743:ios:6c33818d89dbaa945bec3a',
    messagingSenderId: '960456369743',
    projectId: 'ta-app-850bd',
    storageBucket: 'ta-app-850bd.firebasestorage.app',
    iosBundleId: 'com.example.spkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7pfeZgBDQYfOZa5ajxR_vk0Wsp-jrL9U',
    appId: '1:960456369743:web:a63f96fde1b01a325bec3a',
    messagingSenderId: '960456369743',
    projectId: 'ta-app-850bd',
    authDomain: 'ta-app-850bd.firebaseapp.com',
    storageBucket: 'ta-app-850bd.firebasestorage.app',
  );
}
